#!/usr/bin/env bash

function tag_deployment {
  CURRENT_TIMESTAMP=`date "+%Y%m%d%H%M%S"`
  TAG_NAME="deployed_$CURRENT_TIMESTAMP"
  git tag -a -m "Tagging deployment at $CURRENT_TIMESTAMP" $TAG_NAME
}

jekyll && sitecopy --update mike-roda.com && tag_deployment
